# Generated by Django 5.2.1 on 2025-05-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
