# Generated by Django 5.2.1 on 2025-05-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='email_sent',
        ),
    ]
